### PR TITLE
Use ReScript 10

### LINKED ISSUE #396: ReScript 10 compat
Currently according to package.json peer/devDeps, it's not compatible.
But is it ?
I am going to try to adjust locally & see... :)

### PR DESCRIPTION
**Pull request by MoOx**
Closes #396

### CODE REVIEW

**Comment by zth** [comment]
Just wondering, does this mean 10+ is required? If so, can we make it so that 9 is also allowed?

**Comment by MoOx** [comment]
I think we could use ">=9". But in case you start to use v10 feature, it won't work and you might not be aware of it.
Anyway people can always use npm overrides in case they think it's "ok for them to have v9" ?

**Comment by zth** [comment]
I think allowing 9 now as well to start would be ideal. I have a few features in the pipe that will require v10, and at that point I can bump the minimum to v10. Would that be ok for you and your use case too?

**Comment by MoOx** [comment]
Should be ok, I used 10 for devDep, but peerDep to >=9.1.2

**Comment by zth** [comment]
Thank you @MoOx ! Would you also add an entry to the changelog?

**Comment by MoOx** [comment]
@zth done !

**Comment by zth** [comment]
🙏 thank you @MoOx !

**Pull request merged**
