### PR TITLE
fix ci

### PR DESCRIPTION
**Pull request by zth**

### CODE REVIEW

**Comment by DZakh** [comment]
The action versions haven't changed, so there's probably some problem with the GH action runner. Unfortunately, the logs of a passing pipeline have expired, so we can't get the ubuntu version it was using. Have no ideas what happened.

**Comment by zth** [comment]
@DZakh yeah no idea why this has started failing, and I really don't have time to look more into it than I have now, so I'm going to have to postpone a release for now. I got as far as it now being building the Relay Rust compiler on Ubuntu in the release script that fails, but no idea why, and I've tried quite a few things.

**Comment by zth** [comment]
@DZakh it's fixed and out now

**Comment by DZakh** [comment]
Nice, thank you 👍

**Pull request merged**
